/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.user.EditBookCaseView;
import view.user.ReadBook;
import view.user.SearchBookView;
import view.user.ViewBookCase;
import view.user.ViewListBook;

/**
 *
 * @author tuanc
 */
public final class MenuUserView extends javax.swing.JFrame {

    String userName;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * Creates new form MenuUserView
     *
     * @param userName
     */
    public MenuUserView(String userName) {
        setUserName(userName);
        initComponents();
        jLabelUser.setText("Welcome " + userName);
        this.setLocationRelativeTo(null);
    }

    public MenuUserView() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnViewListBook = new javax.swing.JButton();
        btnReadBook = new javax.swing.JButton();
        btnViewBookCase = new javax.swing.JButton();
        btnEditBookCase = new javax.swing.JButton();
        btnbtnBack = new javax.swing.JButton();
        btnSearchBook = new javax.swing.JButton();
        jLabelUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Reading Book Management System");

        btnViewListBook.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnViewListBook.setText("View List Books");
        btnViewListBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewListBookActionPerformed(evt);
            }
        });

        btnReadBook.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnReadBook.setText("Read Book");
        btnReadBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadBookActionPerformed(evt);
            }
        });

        btnViewBookCase.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnViewBookCase.setText("View Your Book Case");
        btnViewBookCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBookCaseActionPerformed(evt);
            }
        });

        btnEditBookCase.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnEditBookCase.setText("Edit Your Book Case");
        btnEditBookCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditBookCaseActionPerformed(evt);
            }
        });

        btnbtnBack.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnbtnBack.setText("Back");
        btnbtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbtnBackActionPerformed(evt);
            }
        });

        btnSearchBook.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnSearchBook.setText("Search Book");
        btnSearchBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBookActionPerformed(evt);
            }
        });

        jLabelUser.setFont(new java.awt.Font("Tempus Sans ITC", 3, 36)); // NOI18N
        jLabelUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUser.setText("Wellcome User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditBookCase, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReadBook, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewBookCase, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewListBook, javax.swing.GroupLayout.PREFERRED_SIZE, 1023, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE))
            .addComponent(jLabelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelUser)
                .addGap(9, 9, 9)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewListBook, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchBook, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnReadBook, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(btnViewBookCase, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEditBookCase, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnbtnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewListBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewListBookActionPerformed
        new ViewListBook().setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_btnViewListBookActionPerformed

    private void btnSearchBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBookActionPerformed
        new SearchBookView().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnSearchBookActionPerformed

    private void btnReadBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadBookActionPerformed
        new ReadBook().setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnReadBookActionPerformed

    private void btnViewBookCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBookCaseActionPerformed
        new ViewBookCase(userName).setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnViewBookCaseActionPerformed

    private void btnEditBookCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditBookCaseActionPerformed
        new EditBookCaseView(userName).setVisible(true);
//        this.dispose();
    }//GEN-LAST:event_btnEditBookCaseActionPerformed

    private void btnbtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbtnBackActionPerformed
//        new LoginView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbtnBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditBookCase;
    private javax.swing.JButton btnReadBook;
    private javax.swing.JButton btnSearchBook;
    private javax.swing.JButton btnViewBookCase;
    private javax.swing.JButton btnViewListBook;
    private javax.swing.JButton btnbtnBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelUser;
    // End of variables declaration//GEN-END:variables
}
